import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header, Sidebar } from '@/components/sections';
import { ScrollArea } from '@/components/ui/scroll-area';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark grid bg-gray-950 w-screen h-screen grid-cols-[16rem_1fr]`}
			>
				<Sidebar />
				<main className='grid grid-rows-[4.5rem_1fr] w-full h-screen overflow-hidden'>
					<Header />
					<div className='flex h-full px-0.5 py-1 w-full overflow-hidden'>
						<ScrollArea className='h-full flex-1 overflow-auto'>
							{children}
						</ScrollArea>
					</div>
				</main>
			</body>
		</html>
	);
}
